make the edit scripts space-safe

diff --git a/Tools/eoaedit b/Tools/eoaedit
--- a/Tools/eoaedit
+++ b/Tools/eoaedit
@@ -1,16 +1,18 @@
 #!/bin/sh
+# Opens the file passed as first parameter with you favourite editor, decrypting it beforehand, encrypting it when you are done.
+# Any additional parameters are passed on to the editor.
 
 if [ -z "$EDITOR" ]; then
-        EDITOR=editor
+	EDITOR=editor
 fi
 
 FILE=$1
 TMPFILE=/tmp/$1.$$.tmp
 shift
-cp $FILE $TMPFILE
-PlasmaCrypt decrypt -quiet $TMPFILE
+cp "$FILE" "$TMPFILE"
+PlasmaCrypt decrypt -quiet "$TMPFILE"
 
-$EDITOR $TMPFILE $@ || echo "Error starting editor, please set EDITOR environment variable"
+"$EDITOR" "$TMPFILE" "$@" || echo "Error starting editor, please set EDITOR environment variable"
 
-PlasmaCrypt aes -quiet $TMPFILE
-cp $TMPFILE $FILE
+PlasmaCrypt aes -quiet "$TMPFILE"
+cp "$TMPFILE" "$FILE"
diff --git a/Tools/uruedit b/Tools/uruedit
--- a/Tools/uruedit
+++ b/Tools/uruedit
@@ -1,4 +1,6 @@
 #!/bin/sh
+# Opens the file passed as first parameter with you favourite editor, decrypting it beforehand, encrypting it when you are done.
+# Any additional parameters are passed on to the editor.
 
 if [ -z "$EDITOR" ]; then
 	EDITOR=editor
@@ -7,10 +9,10 @@ fi
 FILE=$1
 TMPFILE=/tmp/$1.$$.tmp
 shift
-cp $FILE $TMPFILE
-PlasmaCrypt decrypt -quiet $TMPFILE
+cp "$FILE" "$TMPFILE"
+PlasmaCrypt decrypt -quiet "$TMPFILE"
 
-$EDITOR $TMPFILE $@ || echo "Error starting editor, please set EDITOR environment variable"
+"$EDITOR" "$TMPFILE" "$@" || echo "Error starting editor, please set EDITOR environment variable"
 
-PlasmaCrypt xtea -quiet $TMPFILE
-cp $TMPFILE $FILE
+PlasmaCrypt xtea -quiet "$TMPFILE"
+cp "$TMPFILE" "$FILE"
